### ISSUE TITLE
JavaScript error stopping proxy

### ISSUE THREAD

**Issue by futrtrubl** [Xzandro/sw-exporter#129]
Randomly, though they do seem to cluster, I get an error popup while idling in game (running in Nox on the same machine). ~~It doesn't seem to have any effect on functionality that I can see but I tend to restart the applications just in case.~~ Correction, as stated bellow this error does in fact stop the proxy from working.
![untitled-1](https://user-images.githubusercontent.com/5351740/38580279-2a61cafe-3ccf-11e8-8c5e-124affa28e13.png)

**Comment by dotbanana** [comment]
I get this also every day basically. Problem is: For me it stalls the complete network-connection through the proxy and since i run it on a dedicated machine i have always to vnc in and click ok.  
Is a fix for it already in the newly commited stuff? I maybe would try to compile it by myself in this case. Thank you for your work with this great tool :)

![unbenannt](https://user-images.githubusercontent.com/22258372/38782537-6b3095ae-40f5-11e8-98c4-6fdb0e019084.png)

**Comment by futrtrubl** [comment]
Dotbanana is correct, this does in fact stop the proxy from working. So more serious than I had thought/portrayed.

**Comment by Xzandro** [comment]
Hey, this is a common problem with one of our used packages called [node-http-proxy](https://github.com/nodejitsu/node-http-proxy). There are pull requests to fix this, but the project seems kinda dead right now.  So we either wait for a fix or use another package or even write one with oure node http.

**Comment by futrtrubl** [comment]
What about forking the package with the fix and using that?

**Comment by Xzandro** [comment]
Actual great news! They recently made an update to fix a lot of things: https://github.com/nodejitsu/node-http-proxy/releases/latest So I will update this package soon-ish too.
