### ISSUE TITLE
Setting up on a VPS

### ISSUE THREAD

**Issue by dotbanana** [Xzandro/sw-exporter#137]
Hello there, 

thanks for your work with SW-Exporter and the other tools :) 
I saw that you implemented a VPS-mode and that would be really cool then i could power off the windows machine which is constantly running and put the proxy on my homeserver.
But i don't really understand how it should be exactly started in terminal. I am not really keen in node.js and i have a hard time finding information regarding this with google. Can you give some more information on how to start it with the "process environment variables" you mentioned? What do i have to do exactly? Does it have to be set up per node.js-instance or can the script somehow be called with these arguments?

I think a docker-image would come really handy :)  

Thanks in advance

**Comment by Xzandro** [comment]
Hi, well you obviously need node.js on your server. Other than that, I would probably use [pm2](http://pm2.keymetrics.io/) as the process manager. You can then set environment variables via the environment file of pm2: http://pm2.keymetrics.io/docs/usage/application-declaration/ & http://pm2.keymetrics.io/docs/usage/environment/

Keep in mind, that I never actually tested this process, since I use a custom version of SWEX for my [SWEX Web](https://swex.swop.one/) project, but I heard from someone that it worked for him.

**Comment by dotbanana** [comment]
??
I see now where this is going. 
If you going to stop supporting this local version for your centralized thingy to be monetized then there is again need for a new proxy-tool. And i thought we will get a pluginsystem anywhen soon. 
General question: Who really wants a centralized proxy on third party server with considerable lag? People who don‘t own a pc by themselves? That is now the customergroup you aim for? 
I am happy that you pointed out what is planned so i can look somewhere else for what i need...

Good luck making money with this
