### ISSUE TITLE
Javascript Error when SWARFARM is not reachable

### ISSUE THREAD

**Issue by Yawgmoth21** [Xzandro/sw-exporter#189]
![image](https://user-images.githubusercontent.com/47070190/51794652-15277400-219d-11e9-814a-c8ebce44aef3.png)
I get this with the initial start. It seems to happen within a minute of starting the game up. Just started today. otherwise I have been running this without an issue for a while.

**Comment by Xzandro** [comment]
This seems to relate to the SWARFARM downtime currently happening. Tagging @PeteAndersen

**Comment by Psifour** [comment]
This is caused by not checking for an error before using the response object at 

https://github.com/Xzandro/sw-exporter/blob/269c92bc7b78ce0a5df05d8a69071d421ffbbe7d/app/plugins/swarfarm-logger.js#L163-L165

I will add a simple check for the error for now, but a more robust system involving rescheduling the profile upload would be more appropriate (depending on the error type).
