### ISSUE TITLE
[BUG]Can't Connect To The net

### ISSUE THREAD

**Issue by Zekarlo73** [Xzandro/sw-exporter#271]
When I open the application with the proxy configured on my ipad it gives connection error and does not download the information, I have gone to the page that you have indicated to me the deleted the program I have downloaded it again, I have returned to put the certificate and it continues giving the same connection error the clamping does not open if I have configured the proxy I have tried the versions 0.0.27.0.0 .28, 29 and 30 none works and with android does not work either gives the same connection error

**Comment by Xzandro** [comment]
Please read: https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

**Comment by Zekarlo73** [comment]
I have already read this and I have done everything it says and it still does not work so stop sending me the same link as an automatic response and give me some solution

**Comment by Xzandro** [comment]
It would be great, if this would be an automatic response, so I wouldnt need to take time out of my day to respond to these rude and low effort issues.
You didn't even bother to provide meaningful information, like what device, what Android version or iOS version and the actual error message. So stop being rude and entitled and give out information.

Also fun fact: 95% of the errors and issues are caused by people who didn't read the posted reddit thread correctly / carefully enough, forgot steps or other self caused errors.
This repository is for bugs regarding SWEX. These are not bug reports and thus have no place here.

**Comment by Zekarlo73** [comment]
I have not been rude, I have only said that you have automatically sent me the email twice with the link of the redit page despite having said that I had already followed the instructions, my ipad has version 12.4.1, I have Removed version 0.0.30 of swex and deleted all files, I have reinstalled it, I have created the certificate and I have installed it on my iPad and I have run the application with the proxy data configured in my Wi-Fi connection and I always receive the same message
