### ISSUE TITLE
failed to conenct with the network

### ISSUE THREAD

**Issue by Kloc-cpu** [Xzandro/sw-exporter#306]
so what happenes to me is i do evereything i need to connect my phone to the same network and proxy and ip start proxy and basicly me and my brother (programer) found out that the proxy wont work, this leads  to my internet not being usabe and sais that it might not work or sw just shows a black screen ( my brother tried the proxy with some of his methods and it didnt work)

**Comment by Xzandro** [comment]
In general Github isn't to great to have a back and forth discussions why SWEX sometimes doesn't work in your network environment. What I can tell you, that this is probably no general issue with the code. I recommend to use my Discord (https://discord.gg/JMBSZRA) or the reddit mega thread (https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/) to do the troubleshooting.

To give you a few hints what it could possibly be at least

- Entered wrong IP or Port
- SWEX is blocked by some kind of security software (Usually WIndows firewall), happens a lot.
- You are effected by some router weirdness like cliient isolation
- If both devices are connected via Wifi, it could be that both use different frequencies (2.4ghz vs. 5ghz)

I will close this, since its nothing related to the code base and sound smore like an individual network issue.
