### ISSUE TITLE
Its not working for me

### ISSUE THREAD

**Issue by Nabbieshtron** [Xzandro/sw-exporter#321]
I did everything 3 times not working i got certification installed why its so hard to do it.

**Comment by smokedfire** [comment]
Same for me, it worked before but now it doesn't work anymore, can someone please help.

**Comment by breadboi** [comment]
If you're on android, you are required to install a certificate to get the proxy to work now. This isn't any fault of the developer(s) of sw-exporter, since it was com2us who changed over to https.

I recommend following this guide on YouTube to get things working https://youtu.be/mC0IfGJS6MM

You should also take look at this thread to clear things up, as it's much more in-depth.
https://www.reddit.com/r/summonerswar/comments/cxwkav/summoners_war_exporter_swex_everything_you_need/

**Comment by smokedfire** [comment]
Thank you, I had been reading into it and it seems like a lot of work to get this to work.  And it was working earlier this month did they just change it to https recently? Also, do you by chance have a video on blue stacks, if not I will download the other emulator.

**Comment by breadboi** [comment]
I took a break from the game and just got back into it so I have no clue when they changed it.

Also, no clue if there's a blue stacks guide right now, but so long as you're rooted and can transfer the cert to the emulator, the guide should be fairly similar. If you have any trouble, I'd recommend just using nox. @smokedfire

**Comment by smokedfire** [comment]
Alright thanks for all the help

**Comment by Xzandro** [comment]
This isn't a valid bug report. It should work for the majority of people when done correctly within its limitations. If you need support it's recommened to use reddit or Discord.
