### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by T-Birth** [Xzandro/sw-exporter#47]
Used the latest version and after 1-2 Hours this happens.
Switched back to v10/11, runs rock solid 24/7.
![img_1936](https://cloud.githubusercontent.com/assets/20803803/25213286/ee000e6a-258f-11e7-9a4a-c20c9125a883.PNG)

**Comment by Xzandro** [comment]
Would be very helpful to know when this error appeared. (which scenario / dungeon) Obviously it has something to do with the RunLogger. And yea of course 0.0.14 doesnt have that error, because that version doesnt have the RunLogger at all, but that shouldnt be the solution right? I will look at it, more information would have been nice.

**Comment by T-Birth** [comment]
Surely.
This error appeared after 2 Hours proxy uptime during NB10 Runs.

After starting the Run, the proxy crashed and the Game gave out an "Unstable connection error".

My Device:
Samsung S7

My Os:
Windows 8

**Comment by Xzandro** [comment]
Should be fixed with v0.0.17.

**Comment by T-Birth** [comment]
@Xzandro 
You are awesome ! thank you very much !
