### ISSUE TITLE
Proxy seem to be working but no json generated

### ISSUE THREAD

**Issue by NoSleepCrew** [Xzandro/sw-exporter#471]
I'm trying to make this exporter working.
I've tried to run it on windows or on linux but it never work.
Am I missing something
I have seen an recent video showing that it works without https now but it doesn't seem to work on me.
Everything looks fine i can start and connect to the game but no json is generated.
I have laucnh tcpdump to see if there were any packets and I saw a lot of packet on my computer but it did not generate any files.

I'm using the version 0.0.52

Do you have any ideas ?

I am having the same issue. I have tried nearly every combo of settings and such. New certs, https on and off, new certs for https, changed port from 8080 and then back. I tried the "work around" before the latest update to 0.0.52.
I can start the proxy and I can start the game, but I never get the json. I can play the game w/o issue and if I stop the proxy the game stops responding. Then restart the proxy and the game responds again but i never get a json.
Any and all help is appreciated.

**Comment by Natanhel** [comment]
This seems to be the problem for me too.
@Xzandro can you help us solve this?
it seems like SWEX and SWOP are about to die, does anyone plan to support this project any further?

**Comment by NoSleepCrew** [comment]
I did get it to work. Not saying this is the solution, but this is what I did.
Downloaded Nox and then used the Help Guide in SWE to set things up. Once that was done, I got the .json first time up. After that, for grins, I tried again with just my iphone and it worked. I honestly don't know what I did differently that I had not already tried for the iphone.
These are the settings that I have now and it still works on my iphone. Just tested it before writing this.

![adrgadfghadfdfh](https://user-images.githubusercontent.com/121080365/222830646-d3e5286c-09f4-4cdd-87d3-c920a1fa6444.png)

**Comment by Deshaine** [comment]
I've tried the same setup and still can't get it :-(

Any ideas on an fix or an update timeline?

**Comment by Xzandro** [comment]
> This seems to be the problem for me too. @Xzandro can you help us solve this? it seems like SWEX and SWOP are about to die, does anyone plan to support this project any further?

I dont see these projects dying. Both are, on a basic level, well maintained. I usually do not answer to these topics, because this repository is not for generel SWEX help, it is for bugs. And I would not consider this issue a bug, that could be fixed via code.

Ultimately, most of these issues are user errors, not reading the help section and thus skipping a step or not having the newest version installed. Sometimes security software is blocking the access or you are in a network with client isolation.

I get that SWEX might not be the easiest method to export data, but it might be the best we can get. There are no generel issues with SWEX, people still use it daily without issues.

If you need additional help I recommend to [join my Discord](https://discord.gg/JMBSZRA), or open a discussion thread, sicne that is well more suited for general help for SWEX. if you really think, that you found some kind of bug, that can be fixed via code i do not mind issues of course.

Also, this is not on me to maintain SWEX at least. I did so for over 5 years and this is an open sourc eproject for a reason, people can contribute. While I try to continue to maintain the core proxy feature, for everything else, I do not have much time.
