### ISSUE TITLE
A JavaScript Error occured in the process

### ISSUE THREAD

**Issue by Hordil** [Xzandro/sw-exporter#51]
Hello Xzandro,

great project here!
I love how handy this programm is compared to the problem haunted sw proxy, that I stopped using about 2 months ago and switched to your tool after over 1¼yeah of using the proxy.

This message occured now during playing, and will repeat all the time when confirmed:
![screenshot_500](https://cloud.githubusercontent.com/assets/28753744/26149147/7affeec4-3af9-11e7-9df9-a740db9d36f1.png)

Any ideas?

(€dit: Maybe I should take a look if there is an Java Update available )

Best regards,
Hordil

**Comment by Hordil** [comment]
Guess I was just stupid.

I gave my Nintendo Switch the proxy port trying to get a better connection with it some weeks ago, but totally forgot about it and this caused the error. I will tell if this error comes along again ;-)

Best regards,
Hordil

**Comment by Xzandro** [comment]
As an addition: you dont need Java. JavaScript and Java have nothing to to with each other and are completely different programming languages. So if you dont need Java for any other programs, I recommend to deinstall ist from your computer, because its pretty much useless and makes you vulnerable for potential future security issues with it.
