### ISSUE TITLE
Not getting any files

### ISSUE THREAD

**Issue by pedroculos** [Xzandro/sw-exporter#61]
Hello,

For the past few days since the update of summoners war (3.4.5), I am not being able to receive any information from the exporter. I configure my mobile (iOS iPhone 6) with the ip address and the port exactly matching the one that is written on the exporter, then i start the proxy. When the game is done loading I got nothing, the logs are just "now listening to the port..." and there are no profiles saved on my folder. I already reset my wifi and set the password again, typed the ip address and the port 50 times. 

Please if someone could help.

**Comment by hborg004** [comment]
I have the same issue

**Comment by pedroculos** [comment]
Aparently this is dead like sw-proxy

**Comment by Xzandro** [comment]
Its not, sometimes people are busy with life. And most problems are client side anyway. Make sure that you use a hive account. Otherwise the events will be different and no files will be generated. Other than that there are no known issues with it. Most common errors are either entered wrong IP / Port or some kind of security software is blocking the access.
